"""create vendors

Revision ID: d7cced6dbf39
Revises:
Create Date: 2026-09-23 13:52:22.862845
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d7cced6dbf39"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("price_from_kzt", sa.Integer(), nullable=False),
        sa.Column("event_formats", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("max_hours", sa.Integer(), nullable=True),
        sa.Column("busy_dates", postgresql.ARRAY(sa.Date()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("city_imputed", sa.Boolean(), nullable=False),
        sa.Column("price_imputed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vendors")
    # ### end Alembic commands ###
