/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/recommend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recommend */
    post: operations["recommend"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RecommendIn */
    RecommendIn: {
      /**
       * City
       * @enum {string}
       */
      city: "Алматы" | "Астана" | "Зарубежье";
      /**
       * Event Date
       * Format: date
       */
      event_date: string;
      /**
       * Event Format
       * @enum {string}
       */
      event_format: "свадьба" | "той" | "корпоратив" | "конференция" | "юбилей" | "день рождения";
      /**
       * Category
       * @enum {string}
       */
      category:
        | "Ведущий"
        | "Ведущий церемонии"
        | "Фотограф"
        | "Видеограф"
        | "Фото и видеобудки"
        | "Лайв-бэнд"
        | "Инструменталист"
        | "Национальный ансамбль"
        | "Танцевальный коллектив"
        | "Шоу-программа"
        | "Банкетный зал"
        | "Ресторан"
        | "Отель"
        | "Загородная площадка"
        | "Флорист"
        | "Декоратор"
        | "Подарки и сувениры";
      /** Budget Kzt */
      budget_kzt: number;
      /** Duration Hours */
      duration_hours?: number | null;
      /** Languages */
      languages?: ("русский" | "казахский" | "английский")[];
    };
    /** RecommendOut */
    RecommendOut: {
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "matched" | "no_category_in_city" | "no_candidates_pass";
      /** Cards */
      cards: components["schemas"]["VendorCardOut"][];
      /** Pool Size */
      pool_size: number;
      /** Rejections */
      rejections: components["schemas"]["RejectionOut"][];
      /** Suggestions */
      suggestions: components["schemas"]["SuggestionOut"][];
    };
    /** RejectionOut */
    RejectionOut: {
      /**
       * Reason
       * @enum {string}
       */
      reason: "busy" | "format" | "budget" | "duration" | "language";
      /** Count */
      count: number;
    };
    /**
     * SuggestionOut
     * @description A relaxed query that would return more vendors. The frontend can rerun it in one click.
     */
    SuggestionOut: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "date" | "budget" | "city";
      /** Count */
      count: number;
      /** Event Date */
      event_date?: string | null;
      /** Budget Kzt */
      budget_kzt?: number | null;
      /** City */
      city?: ("Алматы" | "Астана" | "Зарубежье") | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VendorCardOut */
    VendorCardOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Categories */
      categories: string[];
      /** City */
      city: string;
      /** Price From Kzt */
      price_from_kzt: number;
      /** Languages */
      languages: string[];
      /** Max Hours */
      max_hours: number | null;
      /**
       * Role
       * @enum {string}
       */
      role: "best_match" | "best_price" | "premium" | "alternative";
      /** Explanation */
      explanation: string;
      /**
       * Explanation Source
       * @enum {string}
       */
      explanation_source: "llm" | "template";
      /** Matched On */
      matched_on: ("date" | "format" | "budget" | "duration" | "language" | "description")[];
      /** Synthetic */
      synthetic: boolean;
      /** Price Imputed */
      price_imputed: boolean;
      /** City Imputed */
      city_imputed: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  recommend: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecommendOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
